---
title: "Chile ISSP gaps"
author: " "
output:
    html_document:
        highlight: tango
---

# The role of meritocratic beliefs on the justification of pay differentials over time

## Short description

- Chile ISSP 1999-2009-2019 perceived and just gaps linked to meritocratic perceptions.
- First abstract version: Request for "Equal Payment" book from Anders Örtenblad, submission out of deadline.
- Second version: for edited book "Perceptions and Misperceptions of Fairness and Inequality" (Nova Publishers), requested by Nadya Columbus. Abstract deadline: 10 August (sent). Chapter deadline: November 2019
- Authors:
  - Juan Carlos Castillo
  - Cristóbal Moya
  - Julio Iturra
  - Luis Maldonado



## Abstract

The growing income concentration has brought about several concerns regarding the fairness of economic differences. Whereas in general terms equality seems to be a justice ideal, on the other hand the differences in income are largely justified based on meritocratic norms of personal effort and talent. In this regard: Are meritocratic beliefs related with differences in perception and justification of unequal payment? Using the social inequality module of the International Social Survey Programme for 1999, 2009 and 2019, this chapter begins describing the perception and justification of salary gaps over 20 years in Chile, followed by an analysis of the role of meritocratic beliefs as predictors of justified salary gaps. A focus of this chapter are the changes in the association between meritocratic beliefs and just salary gaps over time in a society with decreasing poverty as well as high economic inequality as Chile.
